spring:
  datasource:
    url: ${DATABASE_URL}
    username: postgres
    password: parvin
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  servlet:
    context-path: /api
